import requests

url = "http://localhost/CxRestAPI/projects/1/sourceCode/attachments"

payload = "------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"id\"\r\n\r\n29\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"zippedSource\"; filename=\"C:\\Python Scripts\\test.zip\"\r\nContent-Type: application/zip\r\n\r\n\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW--"
headers = {
    'content-type': "multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW",
    'cxOrigin': "WebAPI",
    'Content-Type': "application/x-www-form-urlencoded",
    'Authorization': "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlAwSktwVHVLQ3VRYXdjb1VTa0RaZHZrbzUxVSIsImtpZCI6IlAwSktwVHVLQ3VRYXdjb1VTa0RaZHZrbzUxVSJ9.eyJpc3MiOiJodHRwOi8vREVTS1RPUC1SNkJISUIyL2N4cmVzdGFwaS9hdXRoL2lkZW50aXR5IiwiYXVkIjoiaHR0cDovL0RFU0tUT1AtUjZCSElCMi9jeHJlc3RhcGkvYXV0aC9pZGVudGl0eS9yZXNvdXJjZXMiLCJleHAiOjE1NTYzODQ0OTcsIm5iZiI6MTU1NjI5ODA5NywiY2xpZW50X2lkIjoicmVzb3VyY2Vfb3duZXJfY2xpZW50Iiwic2NvcGUiOiJzYXN0X3Jlc3RfYXBpIiwic3ViIjoiMiIsImF1dGhfdGltZSI6MTU1NjI5ODA5NywiaWRwIjoiaWRzcnYiLCJpZCI6IjIiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbiIsImdpdmVuX25hbWUiOiJhZG1pbiIsImZhbWlseV9uYW1lIjoiYWRtaW4iLCJuYW1lIjoiYWRtaW4gYWRtaW4iLCJMQ0lEIjoiMTAzMyIsImVtYWlsIjoiYWRtaW5AY3guY29tIiwiVGVhbSI6IlxcMDAwMDAwMDAtMTExMS0xMTExLWIxMTEtOTg5YzkwNzBlYjExIiwic2FzdF9yb2xlIjpbInNhdmUtc2FzdC1zY2FuIiwiZGVsZXRlLXNhc3Qtc2NhbiIsInNhdmUtb3NhLXNjYW4iLCJtYW5hZ2UtcmVzdWx0cyIsIm1hbmFnZS1yZXN1bHQtY29tbWVudCIsIm1hbmFnZS1yZXN1bHQtZXhwbG9pdGFiaWxpdHkiLCJtYW5hZ2UtcmVzdWx0LXNldmVyaXR5IiwibWFuYWdlLWRhdGEtYW5hbHlzaXMtdGVtcGxhdGVzIiwidmlldy1kYXNoYm9hcmQiLCJnZW5lcmF0ZS1zY2FuLXJlcG9ydCIsIm1hbmFnZS1xdWVyaWVzIiwib3Blbi1pc3N1ZS10cmFja2luZy10aWNrZXRzIiwibWFuYWdlLWF1dGhlbnRpY2F0aW9uLXByb3RvY29scyIsIm1hbmFnZS1kYXRhLXJldGVudGlvbiIsIm1hbmFnZS1lbmdpbmUtc2VydmVycyIsIm1hbmFnZS1zeXN0ZW0tc2V0dGluZ3MiLCJ1c2Utb2RhdGEiLCJtYW5hZ2UtZXh0ZXJuYWwtc2VydmljZXMtc2V0dGluZ3MiLCJtYW5hZ2UtY3VzdG9tLWRlc2NyaXB0aW9uIiwidmlldy1hcHBzZWMtY29hY2gtc3RhdGlzdGljcyIsIm1hbmFnZS1jdXN0b20tZmllbGRzIiwic2F2ZS1wcm9qZWN0IiwibWFuYWdlLXVzZXJzIiwibWFuYWdlLWlzc3VlLXRyYWNraW5nLXN5c3RlbXMiLCJkZWxldGUtcHJvamVjdCIsIm1hbmFnZS1wcmUtcG9zdC1zY2FuLWFjdGlvbnMiLCJ2aWV3LWZhaWxlZC1zYXN0LXNjYW4iLCJjcmVhdGUtcHJlc2V0IiwidXBkYXRlLWFuZC1kZWxldGUtcHJlc2V0Il0sImFtciI6WyJwYXNzd29yZCJdfQ.nIwy_E1xn8CIRIbeuOti8KIJuVxU4TNlsfpDxt6q_L-PQYhusbesOjcswp7vYOsq2m2u_BAN-ZmSjFcjIe6QAiV9vAJ6JOXpCUEkIk9TkHHajT4WK_wkgS6noHMUN1mHojQRLpKXKDu_6AAYZHisZ9CGbjTfPPx44Ja-2SXAUjsCqLc2K5kNRtGKuekysAhu8dntA-wL7SlA2JZbMUi4doTBvvGQPrAOLL_oUmnxw9iojsA2ch3nMRAy2VstC6pcY7Q_sfG6u4G3BfahJTpt5s7LRHF5239v4tqRpRAtEvDhwoMSZvr2SxGat5ldUB5_aJb8_6d8oP4HHThVejo3WQ",
    'cache-control': "no-cache",
    'Postman-Token': "7c50f9ad-6d0a-42af-9fec-bd9eafb0cce3"
    }

response = requests.request("POST", url, data=payload, headers=headers)

print(response.text)